services:
  postgress:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_USER=sm
      - POSTGRES_PASSWORD=sm_sc
      - POSTGRES_DB=socialconnect
    networks:
      - sc

networks:
  sc:
    name: sc
